### ISSUE TITLE
Memory leak in yaml_malloc

### ISSUE THREAD

**Issue by xcainiao** [yaml/libyaml#113]
git log
```
commit 01f3a8786127748b5bbd4614880c4484570bbd44
Author: Roger Peppe <rogpeppe@gmail.com>
Date:   Mon Jan 8 18:47:02 2018 +0000

    Remove need for PTRDIFF_MAX

    It's just as easy to calculate the maximum value directly.
```
compile
```
gcc -I./  -I./include -g  -fsanitize=address ./leak_1.c -o leak ./src/.libs/libyaml.so
```
[leak_1.c](https://github.com/yaml/libyaml/files/1890022/leak_1.txt)

./leak

error
```
=================================================================
==10850==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3072 byte(s) in 2 object(s) allocated from:
    #0 0x7f7e287af602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f7e2849314c in yaml_malloc /home/fuzz/github/libyaml_g/src/api.c:33
    #2 0x7f7e2849b639 in yaml_document_initialize /home/fuzz/github/libyaml_g/src/api.c:1059
    #3 0x40226e in copy_document leak_1.c:119
    #4 0x402b25 in dumper_main leak_1.c:225
    #5 0x402ecf in main leak_1.c:293
    #6 0x7f7e280e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 1536 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e287af602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f7e2849314c in yaml_malloc /home/fuzz/github/libyaml_g/src/api.c:33
    #2 0x7f7e284e2036 in yaml_parser_load /home/fuzz/github/libyaml_g/src/loader.c:75
    #3 0x402c4c in dumper_main leak_1.c:256
    #4 0x402ecf in main leak_1.c:293
    #5 0x7f7e280e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 44 byte(s) in 2 object(s) allocated from:
    #0 0x7f7e2877930f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f7e284931ec in yaml_strdup /home/fuzz/github/libyaml_g/src/api.c:66
    #2 0x7f7e2849c939 in yaml_document_add_scalar /home/fuzz/github/libyaml_g/src/api.c:1215
    #3 0x4023d4 in copy_document leak_1.c:129
    #4 0x402b25 in dumper_main leak_1.c:225
    #5 0x402ecf in main leak_1.c:293
    #6 0x7f7e280e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 22 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e2877930f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f7e284931ec in yaml_strdup /home/fuzz/github/libyaml_g/src/api.c:66
    #2 0x7f7e284e3964 in yaml_parser_load_scalar /home/fuzz/github/libyaml_g/src/loader.c:293
    #3 0x7f7e284e3083 in yaml_parser_load_node /home/fuzz/github/libyaml_g/src/loader.c:207
    #4 0x7f7e284e2e05 in yaml_parser_load_document /home/fuzz/github/libyaml_g/src/loader.c:184
    #5 0x7f7e284e2414 in yaml_parser_load /home/fuzz/github/libyaml_g/src/loader.c:98
    #6 0x402c4c in dumper_main leak_1.c:256
    #7 0x402ecf in main leak_1.c:293
    #8 0x7f7e280e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e287af602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f7e2849314c in yaml_malloc /home/fuzz/github/libyaml_g/src/api.c:33
    #2 0x7f7e284c4779 in yaml_parser_scan_flow_scalar /home/fuzz/github/libyaml_g/src/scanner.c:3027
    #3 0x7f7e284acae4 in yaml_parser_fetch_flow_scalar /home/fuzz/github/libyaml_g/src/scanner.c:1872
    #4 0x7f7e284a343a in yaml_parser_fetch_next_token /home/fuzz/github/libyaml_g/src/scanner.c:999
    #5 0x7f7e284a107f in yaml_parser_fetch_more_tokens /home/fuzz/github/libyaml_g/src/scanner.c:846
    #6 0x7f7e284d5b20 in yaml_parser_parse_document_content /home/fuzz/github/libyaml_g/src/parser.c:444
    #7 0x7f7e284d3c27 in yaml_parser_state_machine /home/fuzz/github/libyaml_g/src/parser.c:240
    #8 0x7f7e284d3882 in yaml_parser_parse /home/fuzz/github/libyaml_g/src/parser.c:188
    #9 0x7f7e284e2dde in yaml_parser_load_document /home/fuzz/github/libyaml_g/src/loader.c:182
    #10 0x7f7e284e2414 in yaml_parser_load /home/fuzz/github/libyaml_g/src/loader.c:98
    #11 0x402c4c in dumper_main leak_1.c:256
    #12 0x402ecf in main leak_1.c:293
    #13 0x7f7e280e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 9 byte(s) in 2 object(s) allocated from:
    #0 0x7f7e287af602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f7e2849314c in yaml_malloc /home/fuzz/github/libyaml_g/src/api.c:33
    #2 0x7f7e2849c9a2 in yaml_document_add_scalar /home/fuzz/github/libyaml_g/src/api.c:1223
    #3 0x4023d4 in copy_document leak_1.c:129
    #4 0x402b25 in dumper_main leak_1.c:225
    #5 0x402ecf in main leak_1.c:293
    #6 0x7f7e280e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 4699 byte(s) leaked in 9 allocation(s).
```

**Comment by tlsa** [comment]
I tried this, it's not a real leak in libyaml, it's a leak in the provided leak_1.c code.

```diff
--- /home/tlsa/Downloads/leak_1.c  2018-07-19 15:32:14.796672370 +0100
+++ /home/tlsa/Downloads/leak.c    2018-07-19 15:45:46.492523027 +0100
@@ -262,6 +262,11 @@
                 if (!done) {
                     if(!(compare_documents(documents+count, &document) || 0)) {
                       yaml_parser_delete(&parser);
+                      yaml_document_delete(&document);
+                      yaml_parser_delete(&parser);
+                      for (k = 0; k < document_number; k ++) {
+                          yaml_document_delete(documents+k);
+                      }
                       return 0;
                     }
                     count ++;
```

That change (freeing all the stuff before returning) squashes the leak.
